### PR TITLE
fix: outdated stryker

### PR DESCRIPTION
**Pull request by kmdrGroch**

### CODE REVIEW

**Comment by kmdrGroch** [comment]
take a note I removed the yarn.lock (since I'm using npm), remember to update it if you are using lock files

**Comment by scaljeri** [comment]
thanks a lot!!

**Comment by kmdrGroch** [comment]
I hope it works well on your machine too :)

**Comment by scaljeri** [comment]
Yes, I did not expect otherwise, Stryker is an awesome tool! Thanks!

**Comment by kmdrGroch** [comment]
good to hear that!!

**Pull request merged**
